FROM python:3.9-slim

WORKDIR /app

# Instalar MLflow y dependencias básicas
RUN pip install --no-cache-dir mlflow==2.8.1 boto3 pymysql psycopg2-binary

# Crear directorio para MLflow
RUN mkdir -p /mlruns

# Puerto expuesto
EXPOSE 5000

# Comando para iniciar MLflow
CMD ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000", "--backend-store-uri", "file:///mlruns"]

